#Used annotations so that it is not required to create
#Certificate resource manually
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: home
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-cluster-issuer"

spec:
  tls:
  - hosts:
    - home.sandeepchowdary.in
    secretName: letsencrypt-certbot-prod-home
  rules:
  - host: home.sandeepchowdary.in
    http:
      paths:
      - path: /
        backend:
          serviceName: home
          servicePort: 80
