#Used annotations so that it is not required to create
#Certificate resource manually
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"

spec:
  tls:
  - hosts:
    - home.sandeepchowdary.in
    secretName: letsencrypt-certbot-prod-home
  rules:
  - host: home.sandeepchowdary.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-nginx 
            port:
              number: 80
